/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    GlobalLoading: typeof import('./../components/GlobalLoading/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitchDevTool: typeof import('./../components/ThemeSwitchDevTool/index.vue')['default']
  }
}
